version: '3'

networks:
  rmq-net:
    driver: bridge

services:
### RabbitMQ ################################################
    rabbitmq:
      image: "rabbitmq:3-management"
      hostname: "rabbitmq"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      volumes:
        - rmq-etc:/etc/rabbitmq/definitions.json
        - rmq-etc:/etc/rabbitmq/rabbitmq.conf
        - rmq-var:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rmq-var:/var/log/rabbitmq/log
      ports:
        - "15672:15672"
        - "5672:5672"
      labels:
        NAME: "rabbitmq"
volumes:
  rmq-etc:
  rmq-var: